version: 2.1

orbs:
  github-cli: circleci/github-cli@2.6.2

executors:
  docker_lts:
    docker:
      - image: cimg/node:lts

jobs:
  auto_sync_prs:
    executor: docker_lts
    steps:
      - checkout
      # GH_TOKEN as an environment variable -> https://app.circleci.com/settings/project/circleci/Ar3FX8SzxJyoksVDF9xyRr/LZH3jvGmAJqanR2yKDtZ1i/environment-variables?return-to=https%3A%2F%2Fapp.circleci.com%2Fpipelines%2Fcircleci%2FAr3FX8SzxJyoksVDF9xyRr%2FLZH3jvGmAJqanR2yKDtZ1i%2F319%2Fworkflows%2F40703d41-8359-4902-bfbb-a7b9031cb7e1%2Fjobs%2F288
      - github-cli/install
      - run:
          name: Auto sync prs
          command: scripts/auto_sync_prs.sh

  auto_bump:
    executor: docker_lts
    steps:
      - checkout
      - run:
          name: Auto bump version
          command: scripts/auto_bump.sh

workflows:
  build_and_test:
    jobs:
      - auto_sync_prs:
          filters:
            branches:
              only:
                - develop

      - auto_bump:
          filters:
            branches:
              ignore:
                - main
                - develop
