package com.willian.gama.kgp.constants

import com.willian.gama.kgp.constants.CodeAnalysisConstants.LOCAL_PROPERTIES

object SonarConstants {
    const val SONAR_DESCRIPTION = "Analysis generated by Sonar Gradle Scanner"
    const val SONAR_PLUGIN_ID = "org.sonarqube"
    const val SONAR_HOST_URL_PARAM = "sonar.host.url"
    const val SONAR_REMOTE_URL_VALUE = "https://sonarcloud.io"
    const val SONAR_LOCALHOST_URL_VALUE = "http://localhost:9000"
    const val SONAR_TOKEN_KEY_PARAM = "sonar.token"
    const val SONAR_PROJECT_KEY_PARAM = "sonar.projectKey"
    const val SONAR_ORGANIZATION_PARAM = "sonar.organization"
    const val SONAR_PROJECT_NAME_PARAM = "sonar.projectName"
    const val SONAR_KOTLIN_SOURCE_VERSION_PARAM = "sonar.kotlin.source.version"
    const val SONAR_SOURCE_ENCODING_PARAM = "sonar.sourceEncoding"
    const val SONAR_SOURCE_ENCODING_VALUE = "UTF-8"
    const val SONAR_KOTLIN_DETEKT_REPORT_PATHS_PARAM = "sonar.kotlin.detekt.reportPaths"
    const val SONAR_KOTLIN_KTLINT_REPORT_PATHS_PARAM = "sonar.kotlin.ktlint.reportPaths"
    const val SONAR_COVERAGE_JACOCO_XML_REPORT_PATHS_PARAM = "sonar.coverage.jacoco.xmlReportPaths"
    const val SONAR_KTLINT_FILE_PATH = "**/*.json"
    const val SONAR_JACOCO_REPORT_PATH = "reports/jacoco"
    const val SONAR_XML_FILE_PATH = "*.xml"
    fun getMissingPropertyErrorMessage(param: String) = "Code analysis plugin: $param must be included in $LOCAL_PROPERTIES."
}